### ISSUE TITLE
About the training configures for Container-Base model

### ISSUE THREAD

**Issue by ChongjianGE** [allenai/container#1]
Hi,

Thanks for the interesting work and the provided code for container_v1_light.
I would like to ask how many images per batch are used in training the container_base model, since it may simply cause the OOM error when training the container_base model.

**Comment by gaopengcuhk** [comment]
We didn't release container_base. Where do you find container_base?

**Comment by gaopengcuhk** [comment]
container_base is trained with 8 * 48G GPU Memory.

**Comment by gaopengcuhk** [comment]
container_base is trained with 8 * 48G GPU Memory, 128 images per GPU.

**Comment by gaopengcuhk** [comment]
If you need container-base configure, I can share it.

**Comment by ChongjianGE** [comment]
Hi @gaopengcuhk ，
Thanks for the reply on the training details. Speaking of the container_base, I simply change part of the code following the descriptions in the paper. It will be great if you can share the container_base configuration file with me (via rhettgee@connect.hku.hk if it's convenient for you). Thanks again.
